// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpE4ZL4rQ4A-kOy3pHGK_xwppcDNd2R20',
    appId: '1:92070932881:web:2726ba3816a937b2ec6a30',
    messagingSenderId: '92070932881',
    projectId: 'myfirstproject-a0339',
    authDomain: 'myfirstproject-a0339.firebaseapp.com',
    storageBucket: 'myfirstproject-a0339.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvzL8dk-6-RQbMInzL3_yAlmcD4sW_yfI',
    appId: '1:92070932881:android:6beb1f542beb4f32ec6a30',
    messagingSenderId: '92070932881',
    projectId: 'myfirstproject-a0339',
    storageBucket: 'myfirstproject-a0339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtmmQkpv4MBC3AZWFlNHZ4v7wA6v-6ECA',
    appId: '1:92070932881:ios:5b1252b73dc37821ec6a30',
    messagingSenderId: '92070932881',
    projectId: 'myfirstproject-a0339',
    storageBucket: 'myfirstproject-a0339.firebasestorage.app',
    iosBundleId: 'com.example.kite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtmmQkpv4MBC3AZWFlNHZ4v7wA6v-6ECA',
    appId: '1:92070932881:ios:5b1252b73dc37821ec6a30',
    messagingSenderId: '92070932881',
    projectId: 'myfirstproject-a0339',
    storageBucket: 'myfirstproject-a0339.firebasestorage.app',
    iosBundleId: 'com.example.kite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpE4ZL4rQ4A-kOy3pHGK_xwppcDNd2R20',
    appId: '1:92070932881:web:6eca63f566f6c46fec6a30',
    messagingSenderId: '92070932881',
    projectId: 'myfirstproject-a0339',
    authDomain: 'myfirstproject-a0339.firebaseapp.com',
    storageBucket: 'myfirstproject-a0339.firebasestorage.app',
  );
}
